---
apiVersion: v1
kind: Namespace
metadata:
  name: teamspeak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak-deployment
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      namespace: teamspeak
      labels:
        app: teamspeak
    spec:
      containers:
      - name: teamspeak-server
        image: teamspeak
        env:
        - name: TS3SERVER_DB_HOST
          value: 192.168.0.90 # postgres.int.kumpdev.com
        - name: TS3SERVER_DB_PORT
          value: '5432'
        - name: TS3SERVER_DB_NAME
          value: teamspeak
        - name: TS3SERVER_DB_PLUGIN
          value: ts3db_postgresql
        - name: TS3SERVER_DB_SQLCREATEPATH
          value: create_postgresql
        - name: TS3SERVER_DB_USER
          value: teamspeak
        - name: TS3SERVER_DB_WAITUNTILREADY
          value: "30"
        - name: TS3SERVER_LICENSE
          value: accept
        envFrom:
        - secretRef:
            name: teamspeak3dbcreds
        ports:
        - name: "voice"
          containerPort: 9987
          protocol: UDP
        - name: "server-query"
          containerPort: 10011
        - name: "file-transport"
          containerPort: 30033
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-service
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  type: LoadBalancer
  ports:
  - name: "voice"
    port: 9987
    protocol: UDP
    targetPort: 9987
  - name: "server-query"
    port: 10011
    targetPort: 10011
  - name: "file-transport"
    port: 30033
    targetPort: 30033
  selector:
    app: teamspeak
