# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cert-manager
#   namespace: cert-manager
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: 'https://git.kumpdev.com/kumpy/kumpdev-argocd.git'
#     path: cert-manager
#     targetRevision: HEAD
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: cert-manager
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.kumpdev.com/kumpy/kumpdev-argocd.git'
    path: loki-stack
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teamspeak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.kumpdev.com/kumpy/kumpdev-argocd.git'
    path: teamspeak
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: teamspeak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mattermost
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: 'https://git.kumpdev.com/kumpy/kumpdev-argocd.git'
#     path: mattermost
#     targetRevision: HEAD
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: mattermost
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://git.kumpdev.com/kumpy/kumpdev-argocd.git'
    path: caddy
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: caddy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true