---
apiVersion: v1
kind: Namespace
metadata:
  name: caddy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-deployment
  namespace: caddy
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      namespace: caddy
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy-server
        image: caddy
        ports:
        - containerPort: 443
          protocol: UDP
        - containerPort: 443
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: "caddyfile"
            readOnly: true
            mountPath: "/etc/caddy/Caddyfile"
        resources: {}
      restartPolicy: Always
      volumes:
        - name: "caddyfile"
          configMap: 
            name: "caddyfile-configmap"
---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  namespace: caddy
  labels:
    app: caddy
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: UDP
    targetPort: 443
  - port: 443
    protocol: TCP
    targetPort: 443
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: caddy
