apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: teamspeak
  name: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: teamspeak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: teamspeak
    spec:
      containers:
      - image: teamspeak
        name: teamspeak
        env:
        - name: TS3SERVER_LICENSE
          value: accept
        ports:
          - containerPort: 9987
            protocol: UDP
          - containerPort: 10011
          - containerPort: 30033
        resources: {}
      restartPolicy: Always
status: {}
