loki-stack:
  grafana:
    enabled: true
    service:
      type: LoadBalancer
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    server:
      persistentVolume:
        enabled: true
