loki-stack:
  # https://grafana.com/docs/loki/next/installation/helm/reference/
  loki:
    enabled: true
    persistence:
      enabled: true
    gateway:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: loki.kumpdev.com
        paths:
          - path: /
  grafana:
    enabled: true
    service:
      type: LoadBalancer
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    server:
      persistentVolume:
        enabled: true
