loki-stack:
  # https://grafana.com/docs/loki/next/installation/helm/reference/
  loki:
    enabled: true
    persistence:
      enabled: true
    gateway:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
      # annotations:
      #   kubernetes.io/ingress.class: nginx
      hosts: 
        - host: loki.int.kumpdev.com
          paths:
            - /api/prom/push
            - /loki/api/v1/push
            - /api/prom/tail
            - /loki/api/v1/tail
            - /loki/api
            - /api/prom/rules
            - /loki/api/v1/rules
            - /prometheus/api/v1/rules
            - /prometheus/api/v1/alerts
  grafana:
    enabled: true
    service:
      type: LoadBalancer
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    server:
      persistentVolume:
        enabled: true
