loki-stack:
  # https://grafana.com/docs/loki/next/installation/helm/reference/
  loki:
    enabled: true
    persistence:
      enabled: true
    gateway:
      service:
        type: LoadBalancer
  grafana:
    enabled: true
    service:
      type: LoadBalancer
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    server:
      persistentVolume:
        enabled: true
