loki-stack:
  # https://grafana.com/docs/loki/next/installation/helm/reference/
  loki:
    enabled: true
    persistence:
      enabled: true
    gateway:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - host: loki.imkumpy.in
          paths:
            - /
            # - /api/prom/push
            # - /loki/api/v1/push
            # - /api/prom/tail
            # - /loki/api/v1/tail
            # - /loki/api
            # - /api/prom/rules
            # - /loki/api/v1/rules
            # - /prometheus/api/v1/rules
            # - /prometheus/api/v1/alerts

  grafana:
    enabled: true
    persistence:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - grafana.imkumpy.in

  prometheus:
    enabled: true

    alertmanager:
      persistentVolume:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts: 
          - alertmanager.imkumpy.in

    alertmanagerFiles:
      alertmanager.yml:
        global: {
          slack_api_url: 'https://mattermost.kumpdev.com/hooks/7okyo7t1rjd4xgcpp8iz3fu4dc'
        }
        receivers:
          - name: default-receiver
            slack_configs:
              - channel: '#Kumpdev-Alerts'
                send_resolved: true
        route:
          group_wait: 10s
          group_interval: 5m
          receiver: default-receiver
          repeat_interval: 3h

    server:
      persistentVolume:
        enabled: true

    serverFiles:
      ## Alerts configuration
      ## Ref: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
      alerting_rules.yml:
        groups:
          - name: Instances
            rules:
              - alert: InstanceDown
                expr: up == 0
                for: 5m
                labels:
                  severity: page
                annotations:
                  description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
                  summary: 'Instance {{ $labels.instance }} down'

    extraScrapeConfigs: |
      - job_name: 'node-exporter'
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
          - ns1.imkumpy.in:9100
          - ns2.imkumpy.in:9100
          - dockerhost.imkumpy.in:9100
          - omada1.imkumpy.in:9100
          - openvpncloud.imkumpy.in:9100
          - proxmox-1.imkumpy.in:9100
          - syncthing.imkumpy.in:9100
