loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
  grafana:
    enabled: true
    service:
      type: LoadBalancer
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    server:
      persistentVolume:
        enabled: true
      extraScrapeConfigs: |
        - job_name: 'prometheus_external'
          honor_timestamps: true
          scrape_interval: 15s
          scrape_timeout: 10s
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - proxmox.kumpdev.com:9100
