loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
    gateway:
      ingress:
        enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: gateway.loki.kumpdev.com
        paths:
          - path: /
  grafana:
    enabled: true
    service:
      type: LoadBalancer
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    server:
      persistentVolume:
        enabled: true
